
paths:
  checkpoint_dir: checkpoints

preprocessing:
  lowercase: true
  n_val: 500

model:
  d_model: 512
  d_fft: 1024
  encoder_layers: 4
  decoder_layers: 4
  dropout: 0.
  heads: 4

training:
  learning_rate: 0.0001
  batch_size: 32
  epochs: 100
  generate_steps: 1000
  validate_steps: 1000
  checkpoint_steps: 100000
  n_generate_samples: 10