
paths:
  checkpoint_dir: /tmp/checkpoints

preprocessing:
  lowercase: true
  n_val: 100

model:
  d_model: 512
  d_fft: 2048
  encoder_layers: 1
  decoder_layers: 1
  dropout: 0.
  heads: 4

training:
  learning_rate: 0.0001
  batch_size: 32
  epochs: 1000
  generate_steps: 1000
  validate_steps: 1000
  checkpoint_steps: 10000
  n_generate_samples: 5