
paths:
  checkpoint_dir: checkpoints
  data_dir: datasets # directory to store processed data

preprocessing:
  languages: ['de', 'en_us']
  text_symbols: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZäöüÄÖÜß'
  phoneme_symbols: 'abdefhijklmnoprstuvwxyzæçøŋœɐɑɔəɛɡɪʁʃʊʏʒʔˈˌː̥̩̃̍ '
  lowercase: true
  n_val: 500

model:
  d_model: 256
  d_fft: 512
  encoder_layers: 1
  decoder_layers: 1
  dropout: 0.
  heads: 4

training:
  learning_rate: 0.0001
  batch_size: 32
  epochs: 100
  generate_steps: 100
  validate_steps: 100
  checkpoint_steps: 100000
  n_generate_samples: 10
