
paths:
  checkpoint_dir: checkpoints
  data_dir: datasets # directory to store processed data

preprocessing:
  languages: ['de', 'en_us']
  text_symbols: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZäöüÄÖÜß'
  phoneme_symbols: ['a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ç', 'ð', 'ø', 'ŋ', 'œ', 'ɐ', 'ɑ', 'ɔ', 'ə', 'ɛ', 'ɝ', 'ɡ', 'ɪ', 'ʁ', 'ʃ', 'ʊ', 'ʌ', 'ʏ', 'ʒ', 'ʔ', 'ˈ', 'ˌ', 'ː', '̃', '̍', '̥', '̩', '̯', '͡', 'θ']
  char_repeats: 2 # repeating chars of input text to enable mapping to longer phoneme sequences
  lowercase: true
  n_val: 5000

model:
  lstm_dim: 256
  conv_dim: 256
  lang_dim: 32
  d_model: 512
  d_fft: 1024
  layers: 8
  dropout: 0.1
  heads: 8

training:
  learning_rate: 0.0001
  batch_size: 32
  epochs: 100
  generate_steps: 10000
  validate_steps: 1000
  checkpoint_steps: 100000
  n_generate_samples: 10
